package de.raphael.stellwag.spring.meettogether.error;

public enum MeetTogetherExceptionEnum {
    PASSWORD_NOT_CORRECT, EMAIL_DOES_NOT_EXIST, NOT_ALLOWED, USER_NOT_FOUND, EVENT_NOT_FOUND, USER_NOT_IN_EVENT, NO_JWT_IN_AUTHORIZATION_HEADER, EMAIL_ALREADY_EXISTS, TIME_PLACE_SUGGESTION_DOES_NOT_EXIST, USER_ALREADY_IN_TIME_PLACE_SUGGESTION, USER_NOT_IN_TIME_PLACE_SUGGESTION, USER_NOT_CREATOR_OF_EVENT, TIME_PLACE_SUGGESTION_BELONGS_NOT_TO_EVENT;

}
